### ISSUE TITLE
Feature suggestion: has_$option

### ISSUE THREAD

**Issue by srchulo** [jhthorsen/applify#11]
For options, it would be nice to have a `has_$option` method to see if anything was passed in on the command line.

**Comment by jhthorsen** [comment]
I think that will pollute the namespace. What you ask for makes sense coming from Moo(se), but I would just adding a method like `has_option($name)` or just do `exists $self->{$name}`.

I'm sorry, but I won't implement this, but I welcome a PR for discussion.

**Comment by srchulo** [comment]
Okay, thanks! I will try to work on a pull request.

**Comment by kiwiroy** [comment]
Namespace pollution was my first concern too. Also, what to do with options that have a default specified, what is the expectation there?

```perl
sub has_option ($self, $name) {
    $name = $self->_script->_option_to_attr($name);
    return !!(exists $self->{$name});
}
## or
sub user_specified_option ($self, $name) {
    $name = $self->_script->_option_to_attr($name);
    my ($option) = grep { $_->{name} eq $name } @{$self->_script->options};
    return unless $option;
    return !!($self->{$name} ne $option->{default});
}
```

The other use case that might be useful is the script has a few options, one of them should be specified, but none of them are `required`. It might then make sense to have a method like `Applify::empty_argv_shows_help()` which might get the flag it would set checked after the subcommand activation.

https://github.com/jhthorsen/applify/blob/df2b22ba4ea09a34e4745332ebbe4775496887b4/lib/Applify.pm#L24-L25

`$self->print_help->_exit('help') if 0 == @ARGV && $self->{empty_argv_shows_help};`

Doing this is a script takes some work that might be best done in Applify.

**Comment by srchulo** [comment]
I guess I don't understand the concern with namespace pollution? To me it seems convenient and better than the user having to do:

`!!(exists $self->{$name});`

I'm personally not a fan of `has_option` where you pass in a name, since each option gets their own method and isn't `option($self, $name)`.

What I was expecting for when there are defaults is to handle it like Moose and say `true` if there is a value, although `has_user_specified_option` could also be useful.

For that last use case you mention I'm a little confused what you mean and how it's related.

**Comment by kiwiroy** [comment]
@srchulo with a Moose based class `has_$option` is present as expected.

https://github.com/jhthorsen/applify/blob/df2b22ba4ea09a34e4745332ebbe4775496887b4/t/moose.t#L39-L42

I think I'm less concerned with namespace pollution now I've seen `_sub()` does the right thing.

`!!(exists $self->{$name});` isn't enough ...sigh... all options get a default of at least `undef`.

Otherwise, I was musing possible use cases and discerning more about expectations for this feature.

**Comment by jhthorsen** [comment]
I think I agree on all of the comments. Going to close this in favour of #13.

👍

**Comment by srchulo** [comment]
Thanks, guys! The changes look great. @kiwiroy, the one thing I wonder is if the documentation should make clear that providing a default of `undef` will cause `has_$option` to be false? I do think this makes sense, since there's no way to pass in `undef` via an argument.
