### ISSUE TITLE
Feature suggestion: ability to disallow unknown options

### ISSUE THREAD

**Issue by srchulo** [jhthorsen/applify#12]

**Comment by jhthorsen** [comment]
Isn't that just:

```
app {
  my $self = shift;
  die "..." if @_;
};
```

Please explain which behavior you want, if that's not the case.

**Comment by srchulo** [comment]
Sorry, yes. That is the behavior that I meant.

**Comment by srchulo** [comment]
Would you be willing to consider a pull request if I made one? Or is this not a feature that you want?

**Comment by jhthorsen** [comment]
Oh. I misunderstood. I thought you meant that you could use that die() instead.

I don’t see how it will be easier to add this to Apllify, so you need to make a case for it.

**Comment by srchulo** [comment]
The main use case that I see here is that someone mistypes an optional argument and isn't aware that they typed it wrong. 

My case for it is just that I think that it's a common enough use case for an argument parsing library, and it would be nice if everyone didn't have to reimplement it who wanted this.

**Comment by srchulo** [comment]
I actually think it makes sense as a default, and then allow extra arguments if you want that. However, this probably wouldn't be an option now anyway since it would be backwards incompatible with existing programs.

**Comment by jhthorsen** [comment]
I won’t make that change for two reasons:

1. It will be a breaking change.
2. My apps are the complete opposite: most of them use the extra arguments.

My problem with this issue is that `die if @_` is shorter than anything else I can come up with.

About the misspelled arguments: would be nicer if we had a module that can guess that and say things like “did you mean...”.

**Comment by kiwiroy** [comment]
I like the *did you mean*. For one app I copied the Levenshtein sub from `cpanm` IIRC. I’d really see benefit for the sub commands more than options.

**Comment by srchulo** [comment]
@jhthorsen I agree that `die if @_` is short, but making it a method could mean that Applify could describe this behavior in the help, and it could also create the error message when unknown arguments are provided. I think that adding something like Levenshtein makes that feature more appealing, because that does add more behavior than just `die if @_` that everyone could benefit from.

**Comment by jhthorsen** [comment]
See also #20.
