### ISSUE TITLE
Feature Request: Support required mutually exclusive groups

### ISSUE THREAD

**Issue by srchulo** [jhthorsen/applify#14]
It would be great to have a feature like argparse's [mutual exclusion](https://docs.python.org/3/library/argparse.html#mutual-exclusion) where exactly one option in a list of options is required:

```
>>> parser = argparse.ArgumentParser(prog='PROG')
>>> group = parser.add_mutually_exclusive_group()
>>> group.add_argument('--foo', action='store_true')
>>> group.add_argument('--bar', action='store_false')
>>> parser.parse_args(['--foo'])
Namespace(bar=True, foo=True)
>>> parser.parse_args(['--bar'])
Namespace(bar=False, foo=False)
>>> parser.parse_args(['--foo', '--bar'])
usage: PROG [-h] [--foo | --bar]
PROG: error: argument --bar: not allowed with argument --foo
```

**Comment by kiwiroy** [comment]
I like this idea.

Any thoughts on semantics of the interface?

Also, are there any tricks in `Getopt::Long` we can leverage?

**Comment by kiwiroy** [comment]
How does this look?

```perl
group_options {
  option str => a => "alpha", ...;
  option str => b => "beta", ...;
}, "exclusive", ...;
```

**Comment by srchulo** [comment]
I think that looks good! And I guess we would need to make sure that this worked within the subcommands. 

What is the exclusive for after the group_option? Would there be other values that you think would make sense there?

**Comment by kiwiroy** [comment]
I think subcommands will just work, but yes, will require checking

Something that means *at least one*. We could just use `"required"` to mean that? I'm not sure what [argparse](https://docs.python.org/3/library/argparse.html#argument-groups) has that though.

**Comment by kiwiroy** [comment]
@srchulo 02640c0 on the group-options branch, while a bit rough, is worth a look if you have time.

**Comment by srchulo** [comment]
Oh, I like the idea of at least one.

**Comment by jhthorsen** [comment]
I feel the usecase is not common enough to make part of Applify. What's wrong with just keeping it simple like:

```
app {
  my $self = shift;
  die "Sorry, no can do!" if $self->option_a and $self->option_b;
};
```

(I think that I would rather add support for plugins instead)

**Comment by srchulo** [comment]
So that's what I'm currently doing, but I'd prefer if Applify did it for me. I also see this use case a lot, so I'd love for it to be in Applify and defined with the rest of the options config instead of separate in `app`.

If it isn't common enough though, I do like the idea of plugins.

**Comment by srchulo** [comment]
For me the main issue is that in Perl I've had a hard time finding a fully featured argument parsing library. I write most of my code in Perl, but I've always had a difficult time coming from argparse in Python or argparse4j in Java. I really enjoy Applify, and its argument parsing and the documentation output is the best I've found, but personally I prefer to have an over-featured argument parsing library, than me having to write additional argument parsing on top of the arg library that I'm using.

However, I do think that if you want to keep Applify really simple, plugins would be great so that people could get more feature rich argument parsing without building it themselves, and build on the great base that Applify has.

**Comment by jhthorsen** [comment]
Thanks for the kind words. I really appreciate it. If this feature is added then I need to know how this will be documented in the `--help` output? I don't think I've used a program with this feature before, so I don't know how this would look. Please provide an example output from such a program in a comment.

I also wonder if we can use the existing `option` function for this, like:

    option bar => '...' => excludes => 'foo';
    option foo => '...' => excludes => 'bar';

It looks a bit weird, but we would make `excludes` only required on one of the attribute, if that helps. The reason why I like this is that I think it's more flexible. We could for example add `requires => 'foo'` as well by extending `@args` - if we find a way to document it ;)

**Comment by jhthorsen** [comment]
Another idea would be to set up the options first and then define rules later on, such as:

```
option foo => '...';
option bar => '...';
option baz => '...';
option_rules exclusive => ['foo', 'bar']; # Can be called as many times as you want
```

I'm not a huge fan of this one, since it requires a new function, but I'm throwing the idea out there anyways.

**Comment by kiwiroy** [comment]
@jhthorsen I'd second what @srchulo has said, specifically

> I really enjoy Applify, and its argument parsing and the documentation output is the best I've found

I'm also concerned about the command line interface documentation (`--help`). `--man` is easy, the pod can be as verbose as needed.

There's not a whole lot of space at the command line so information density has to be quite high, but also have clarity, so as not to confuse.

argparse.print_help() looks like this and would be quite easy to emulate based on `$self->{options}{$name}{$group}`, but I wonder if we could do better.
```
usage: PROG [-h] [--foo | --bar]

group1:
  group1 description

  --foo      foo help
  --bar BAR  bar help
```
&nbsp;

> We could for example add `requires => 'foo'`

I like this idea, but I'm not sure that the `group_options {} $name => $mode` alters ability
to implement that. `option` is still an option, inside or outside of the group and referencing a option not part of the current group wouldn't be limited. Using a named group would also allow for, when `--foo` is specified one of group `bar` should be specified too.

The thing I like about `group_options` is it's very difficult to get wrong as a user. There's no scope for mis-typing the name of another option, or even mis-typing `exclude` etc...

**Comment by jhthorsen** [comment]
That example output with "group1" is not very intuitive imo. We must be able to do that better. I can't say I understand the concept of "groups", since a group is not something I connect with exclusiveness.

You're right that `group_options` does not limit the addition of "requires".

We could easily figure out if the `exclusive` options are present or not. I would urge us to do exactly that, so we add "exclusiveness" to the other options that does not have it specified. Example:

```
option bar => '...' => excludes => 'foo';
option foo => '...'; # <-- will automatically get "excludes => bar", since that is defined by the "bar" attribute.
```

**Comment by kiwiroy** [comment]
Unicode?
```
  option-groups.pl [options]

Examples:

  option-groups.pl -text -json -perl

Usage:
   --json    ┓  output json
   --yaml    ┫∞ output yaml
   --text    ┛  output text
   --perl    ┓  perl version
   --name    ┛∨ name list
   --verbose    debug

   --help       Print this help text
   --man        Display manual for this application
   --version    Print application name and version
```
I used infinity and logical or, but could be
* any &#20961;
* exclusive &#14656;

**Comment by srchulo** [comment]
@kiwiroy is Unicode well supported on most terminals? I think that looks great, but I wonder if any users will be left out?

@jhthorsen 

> We could for example add `requires => 'foo'`

I also really like this idea. This is another ability that I've wanted before :)

@jhthorsen I think that this makes sense:

> If not adding "excludes" automatically, then I think we should die with a message that excludes are not set up right.

**Comment by jhthorsen** [comment]
I think that’s hard to read and I also want the order to be alphabetic, which won’t work in this case.

How about just writing something like “This option excludes —bar” or “This option cannot be used together with —bar” on a new line below the description?

**Comment by jhthorsen** [comment]
I'm going to close this issue, since I don't think the complexity is worth it. I will consider a PR with example output, but I can't guaranty it will get merged.
