### ISSUE TITLE
Feature Request: enum type

### ISSUE THREAD

**Issue by srchulo** [jhthorsen/applify#15]
I think that an enum type would be useful:

`option enum => fruit => ['apple', 'banana', 'orange'] => 'Fruit to eat';`

Where the provided value must be one of the types listed in the array ref.

**Comment by jhthorsen** [comment]
Do you have a real example where this is useful?

**Comment by srchulo** [comment]
One example I had recently was downloading data for only a select list of vendors. Right now I check myself:

```
perl download.pl --vendor vendor_xyz
...
app {
     my ($self) = @_;
     die unless grep $self->vendor eq $_, @vendors;
}
```

Another example I've run into is file output formats when there's only a few that are allowed.

It can also be useful for modes when you have more than two, where just something like a verbose `flag` won't work.

**Comment by jhthorsen** [comment]
I'm not going to actually implement "enum" logic into Applify. What I am open to however is to allow "isa" to work, even if you are not inheriting from Moose.

Types::Standard seems very lightweight, so I think we should rather support this:

```
use Types::Standard 'Enum';
option str => vendor => '...' => isa => Enum[qw(foo bar baz)];
```

I'll take a PR with that functionality, as long as it supports coercion as well. A bonus would be if "coercion" is also supported.

**Comment by srchulo** [comment]
Ah, that's a good idea! I'll try to work on getting something up for you to look at in the next few days.

**Comment by jhthorsen** [comment]
I'm going to close this issue, since I think the title does not encapsulate the new proposed solution.

Looking forward to the PR 👍

**Comment by kiwiroy** [comment]
@srchulo I had a little bit of time yesterday to look - see https://github.com/jhthorsen/applify/compare/master...kiwiroy:enum-types

Feel free to continue that. Some things I checked out as working with this.
```
use Types::Standard qw{Enum Str};
option str  => vendor => '...', isa => Enum[qw{foo bar baz}];
option str  => foo => '...', isa => (Enum[qw{foo bar baz}])->plus_fallback_coercions(Str() => q{"foo"});
```

**Comment by jhthorsen** [comment]
@kiwiroy: Your version did not consider what would happen if you change an attribute during runtime, so I created a PR.
