### ISSUE TITLE
Passing options to Getopt::Long

### ISSUE THREAD

**Issue by vague666** [jhthorsen/applify#19]
There seems to be no obvious way to pass options to `Getopt::Long` before passed arguments are parsed
One terrible way(thanks to haarg) is to use
`extends()->option_parser(Getopt::Long::Parser->new(config => [qw(no_auto_help pass_through bundling)]));
`
Doing it the documented way inside `app {}` appears to be too late in the process and $self is not defined outside `app {}`

If there is a recommended way that works it needs to be better documented

**Comment by jhthorsen** [comment]
Where is it documented that you should change option_parser inside `app {}`?

Either way, you're absolutely right that there's no obvious way to change it, without subclassing Applify or using another hack.

How do you suggest we solve this? Export a function `script` or `applify`? Or a `$SCRIPT` variable? Allow options to be passed to `app {}, option_parser => ...;` ?

I'm not sure what would be the best way.

**Comment by vague666** [comment]
It's not obvious where to change `option_parser` and since the example uses `$self` it would only work inside `app {}` without subclassing, so some clarification would be needed
Best way to solve is a tricky question, everybody has an opinion on how to best do it :)
Having access to `script` would probably be best imo, however that can be done

**Comment by kiwiroy** [comment]
Given you are wanting to change comprehension of options, `option` would be a better way to get hold of the object, no?
```perl
use Applify;

option(file => input => 'file to read')
  ->option_parser
  ->configure(qw{no_auto_help pass_through bundling});

option flag => debug => 'verbose output';

app {
  my $app = shift;
};
```

**Comment by jhthorsen** [comment]
@kiwiroy: It's not intuitive. At least not to me.

**Comment by srchulo** [comment]
I agree that the above is not particularly clear.

**Comment by jhthorsen** [comment]
I've fixed this by introducing "hooks". Hope this works for you!

**Comment by srchulo** [comment]
Just checked out the documentation-- looks great!!
