### ISSUE TITLE
multiple values option doesn't show help '+' if also required

### ISSUE THREAD

**Issue by srchulo** [jhthorsen/applify#22]
If you have an option that uses `n_of` and sets `required => 1`, then only the required asterisk will show in the help, and not the `+`:

```
option str => multi => 'Accepts multiple values' => required => 1 => n_of => '@';
```

And the output:

```
Usage:
 * --multi  Accepts multiple values

   --help   Print this help text

Notes:
 * denotes a required option
 + denotes an option that accepts multiple values
Required attribute missing: --multi
```

**Comment by jhthorsen** [comment]
I changed it into this now:

```
 *  denotes a required option
 +  denotes an option that accepts multiple values
 ++ denotes an option that accepts multiple values and is required
```

Hope that works for you.

**Comment by srchulo** [comment]
Thanks! Small thing, why `++` instead of something like `*+` or `* +`? Not a big deal, but it does seem a little strange to me that `*` means required, `+` means multiple, but `++` means required and multiple.

**Comment by jhthorsen** [comment]
I found `*+` hard to read, so that's why I didn't choose that one.

**Comment by srchulo** [comment]
That's fair 👌
