### ISSUE TITLE
n_of with repeater only returns last value

### ISSUE THREAD

**Issue by srchulo** [jhthorsen/applify#23]
I am trying to use the `n_of` feature with the value `"1,2"`, however, only the last value gets put into the option:

```
use Applify;
use Mojo::Base -strict;

option str => repeater => 'Give me one to two things' => required => 1 => n_of => '1,2';

app {
    say shift->repeater;

    0;  
}
```

```
perl test.pl --repeater hello world

# output:
world
```

**Comment by jhthorsen** [comment]
I thought `n_of => '1,2'` would automatically create an array-ref, but by reading the documentation closer I found out that it needs to be predefined.

This is fixed now. Thanks for reporting in!

**Comment by srchulo** [comment]
Awesome! Thanks for the fix :)
