### ISSUE TITLE
Meant to work with Moo/OO helpers?

### ISSUE THREAD

**Issue by srchulo** [jhthorsen/applify#24]
I have this example class:

```
use Applify;
use Moo;

has cat_sound => (
    is => 'ro',
    default => sub { "meow!\n" },
);

sub meow_plz () {
    print shift->cat_sound;
}

app {
    shift->meow_plz;
}
```

Which gives me these warnings when run and prints nothing:

```
Use of uninitialized value in string eq at /usr/local/share/perl5/Sub/Defer.pm line 88.
Use of uninitialized value in print at cat.pl line 10.
```

Is Applify meant to play with OO frameworks? I get a similar result with Moose:

```
Use of uninitialized value in print at cat.pl line 10.
```

But Mojo::Base actually seems to work:

```
use Applify;
use Mojo::Base -base;

has cat_sound => sub { "meow\n" };

sub meow_plz () {
    print shift->cat_sound;
}

app {
    shift->meow_plz;
}
```

prints `meow!`

**Comment by kiwiroy** [comment]
Your code needs to notify `Applify` that it's inheriting, because Moo exports `extends` also, use the import arguments to `Applify` thus:
```perl
use Applify extends => 'app_extends';
use Moo;

app_extends 'Moo::Object';

has cat_sound => (
    is => 'ro',
    default => sub { "meow!\n" },
);

sub meow_plz () {
    print shift->cat_sound;
}

# this removes warning
# Sub::Defer::undefer_package(__PACKAGE__);
# so does this
# __PACKAGE__->new;

app {
    shift->meow_plz;
    return 0;
}
```
That said I still get the warning from `Sub::Defer` hence the call to `undefer_package`, but that can't be the fix - I think it is the `new` method's fault.

**Comment by jhthorsen** [comment]
There's already support for https://github.com/jhthorsen/applify/blob/master/lib/Applify.pm#L362, so maybe there would be a way to add support for Moo as well? I'll take a PR for that 😄

**Comment by kiwiroy** [comment]
@jhthorsen any idea why the warning from `Sub::Defer`?

**Comment by jhthorsen** [comment]
No. I don't use Moo, nor Moose. (That's why I asked for a PR)

**Comment by srchulo** [comment]
@jhthorsen the above example actually doesn't seem to work with Moose. I switched `Moo::Object` to `Moose::Object` and I just get this warning:

```
Use of uninitialized value in print at cat.pl line 12.
```

**Comment by jhthorsen** [comment]
Does that mean that https://github.com/jhthorsen/applify/blob/master/t/moose.t no longer runs?

**Comment by srchulo** [comment]
So it looks like `moose.t` runs and passes, I guess the difference there is that it is extending a different package vs the same package that `Applify` is used in?

```
  eval q[
    package My::Class;
    use Moose;
    has exit_value => (is => 'ro', default => 123);
    has o_foo => (is => 'ro', lazy_build => 1);
    sub _build_foo { -1 }
    sub do_stuff { print "some stuff...\n" }
    __PACKAGE__->meta->make_immutable;
    $INC{'My/Class.pm'} = 'MOCK';
  ] or die $@;

  local @ARGV = qw(--o-bar 24 --o-foo 42);
  my $app = eval q[
    use Applify;
    extends 'My::Class';
    option int => o_foo => 'Some option';
    option int => o_bar => 'Some option';
    app {
      my $self = shift;
      $self->do_stuff;
      return $self->exit_value;
    };
  ] or die $@;
```

**Comment by jhthorsen** [comment]
My comment at https://github.com/jhthorsen/applify/issues/24#issuecomment-532148623 was invalid, since it inherits from a Moose class.

I'm still not interested in this, but I'll take a PR.

**Comment by jhthorsen** [comment]
I'm going to close this issue since it is quite old now. Please open an PR.
