### ISSUE TITLE
warning produced: uninitialized value $length in numeric lt (<)

### ISSUE THREAD

**Issue by srchulo** [jhthorsen/applify#26]
When you run this script without providing any options or with `--help`:

```
use Applify;

option file => input_file => 'input file' => required => 1 => isa => 'Mojo::File';

app {
    my $self = shift;

    say $self->input_file;

    0;
}
```

```
perl applify.pl
```

This warning is produced:

```
Use of uninitialized value $length in numeric lt (<) at /home/user/perl5/perlbrew/perls/perl-5.30.0/lib/site_perl/5.30.0/Applify.pm line 173.
Use of uninitialized value $length in numeric lt (<) at /home/user/perl5/perlbrew/perls/perl-5.30.0/lib/site_perl/5.30.0/Applify.pm line 173.
```

**Comment by kiwiroy** [comment]
I’ve seen this too, but haven’t investigated.

**Comment by srchulo** [comment]
It looks like it's coming from the two hashrefs [here](https://github.com/jhthorsen/applify/blob/master/lib/Applify.pm#L164) in `print_help`:

```
my @options = (@{$self->options}, {}, @{$self->_default_options}, {});
```

Looks like those were introduced in 17c1ddf892b448ad83ac260b6f316d6053f47065 in the fix for #23.

I think they were added to serve as newlines between the user provided options and the default options, and a line after the default options. Maybe the fix would be something like this?

```
OPTION:
  for my $option (@options) {
    my $name = $option->{name} or next OPTION;
    my $length = length $name;
    $width = $length if $width < $length;
  }

# or

OPTION:
  for my $option (@options) {
    next OPTION unless %$option;
    my $length = length $name;
    $width = $length if $width < $length;
  }
```

**Comment by jhthorsen** [comment]
I'm guessing your perl is very old. Which version are you running?

**Comment by srchulo** [comment]
I'm using 5.30.

**Comment by djerius** [comment]
I'm seeing the same behavior on Perl 5.28.1, Applify version 0.19

**Comment by jhthorsen** [comment]
I messed up reading the line numbers. I see the problem now. Sorry for the delay.
