### ISSUE TITLE
support for loading configuration files

### ISSUE THREAD

**Issue by djerius** [jhthorsen/applify#28]
Here's what I've hacked up to provide the user the ability to specify command line options via a configuration file:

```
# use Applify hook to add configuration file processing
hook before_options_parsing => sub ( $script, $argv ) {
    my $file;

    require Getopt::Long;
    my $parser = Getopt::Long::Parser->new( config => [ 'pass_through' ] );
    $parser->getoptionsfromarray( $argv, 'cfg|f=s', \$file );

    return unless defined $file;

    my $cfg = Config::Any->load_files( {
            files           => [ $file ],
            use_ext         => 1,
            flatten_to_hash => 1,
        } )->{ $file };

    for my $opt ( keys $cfg->%* ) {
        next unless grep { $_->{arg} eq $opt } $script->options->@*;
        unshift $argv->@*, "--$opt", $cfg->{$opt};
    }
};

# this global option isn't really used, as the configuration
# file reading is done via the above before_options_parsing hook,
# but it adds documentation.
option file => cfg => 'configuration file' => alias => 'f';
```
As you can see, it adds a lot of boilerplate code.

It'd be nice if  configuration file parsing were part of Applify.  Perhaps something along the lines of

`option config => cfg => 'configuration file';`

**Comment by jhthorsen** [comment]
I don't really want to add support for config files, since there's a million ways to do it. (And I'm not a fan of Config::Any)

At this point I think we should add (optional) support for roles instead, so you can apply a role with options and methods.
