### ISSUE TITLE
Feature Request: Nested subcommands

### ISSUE THREAD

**Issue by adam-stokes** [jhthorsen/applify#30]
Not sure if this is a good use case for Applify but I couldn't find anything I liked on metacpan.org for supporting nested subcommands (MooX::Cmd, MooX::Commander)

But I was thinking something like:

```
version 0.01;
documentation __FILE__;

subcommand repo => 'Repo management' => sub {
    option str  => items => "Path to repo items", required => 1, n_of => 1;

    subcommand sync => 'Repo Sync' => sub {
        option str => upstream, required => 1;
    };
};

sub command_repo_sync {
    # Stuff here
}

sub command_repo {
  my $app    = shift;
  return 0;
}

app {
  my $self = shift;
  return 0;
};
```

Which would give the ability to do `<app> repo sync --upstream ...` and that just be tied to that nested subcommand `sync`.

Thoughts?

**Comment by jhthorsen** [comment]
I don’t mind this, but I’m also not interested enough to implement it.

PR is welcome :)

**Comment by jhthorsen** [comment]
Going to close this issue because it is quite old.

PR is still welcome though!
